services:
  php:
    container_name: pdf-php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./documents:/documents:ro,cached
      - ./generators/php:/php:rw,cached
      - ./output:/output:rw,cached

  python:
    container_name: pdf-python
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./documents:/documents:ro,cached
      - ./generators/python:/python:rw,cached
      - ./output:/output:rw,cached

  ubuntu:
    container_name: pdf-ubuntu
    build:
      context: ./
      dockerfile: ./docker/ubuntu/Dockerfile
    volumes:
      - ./documents:/documents:ro,cached
      - ./generators/ubuntu:/ubuntu:rw,cached
      - ./output:/output:rw,cached
